"""
Trading Engine Package

This package contains the core backtest execution engine generated by /build-engine.
It provides realistic trading simulation with proper timing, fees, and risk management.
"""

__version__ = "1.0.0"
__author__ = "Trading Engine Builder"

from .backtest import BacktestEngine
from .core.strategy_interface import StrategyInterface
from .core.portfolio_manager import PortfolioManager

__all__ = [
    "BacktestEngine",
    "StrategyInterface", 
    "PortfolioManager"
]